In [2]:
import pandas as pd
from pathlib import Path
rd = Path.cwd().parent/'data'/'raw/'
wd = Path.cwd().parent/'data'/'processed/'

In [3]:
df = pd.read_csv(rd/'02_nav_history.csv')
df['date']=pd.to_datetime(df['date'])
df['date']

0       2022-01-03
1       2022-01-04
2       2022-01-05
3       2022-01-06
4       2022-01-07
           ...
45995   2026-05-25
45996   2026-05-26
45997   2026-05-27
45998   2026-05-28
45999   2026-05-29
Name: date, Length: 46000, dtype: datetime64[us]

In [4]:
df.sort_values(by=['amfi_code','date'])
df = df.drop_duplicates()
df = df[df['nav']>0]

In [5]:
df.set_index('date')

            amfi_code       nav
date
2022-01-03     119551   54.3856
2022-01-04     119551   54.3474
2022-01-05     119551   54.6869
2022-01-06     119551   55.4550
2022-01-07     119551   55.3692
...               ...       ...
2026-05-25     149324  292.4810
2026-05-26     149324  291.2707
2026-05-27     149324  288.8007
2026-05-28     149324  280.6873
2026-05-29     149324  279.7511

[46000 rows x 2 columns]

In [6]:
df2=[]
for amfi_code, group in df.groupby('amfi_code'):
        group = group.set_index('date')
        
        full_date_range = pd.date_range(start=group.index.min(), end=group.index.max(), freq='D')
        
        group = group.reindex(full_date_range)
        group['amfi_code'] = amfi_code  # Populate the amfi_code for the newly created rows
        
        group['nav'] = group['nav'].ffill()
        
        group = group.reset_index().rename(columns={'index': 'date'})
        df2.append(group)

In [7]:
final_df = pd.concat(df2, ignore_index=True)
    
final_df = final_df.sort_values(by=['amfi_code', 'date']).reset_index(drop=True)

In [8]:
final_df

            date  amfi_code       nav
0     2022-01-03     100016  520.4608
1     2022-01-04     100016  515.0971
2     2022-01-05     100016  521.7239
3     2022-01-06     100016  515.7880
4     2022-01-07     100016  515.1639
...          ...        ...       ...
64315 2026-05-25     149324  292.4810
64316 2026-05-26     149324  291.2707
64317 2026-05-27     149324  288.8007
64318 2026-05-28     149324  280.6873
64319 2026-05-29     149324  279.7511

[64320 rows x 3 columns]

In [9]:
final_df.to_csv(wd/'clean_nav.csv',index=False)

In [10]:
#2nd cleaning

df_it = pd.read_csv(rd/'08_investor_transactions.csv')
df_it['transaction_date'] = pd.to_datetime(df_it['transaction_date'])

In [11]:
df_it[df_it['amount_inr']<=0]
#all valid
df_it.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [12]:
df_it['transaction_type'].unique()

<StringArray>
['SIP', 'Redemption', 'Lumpsum']
Length: 3, dtype: str

In [13]:
df_it['kyc_status'].unique()

<StringArray>
['Verified', 'Pending']
Length: 2, dtype: str

In [14]:
df_it.to_csv(wd/'clean_transactions.csv',index=False)

In [15]:
#3rd cleaning
df_sp = pd.read_csv(rd/'07_scheme_performance.csv')
print(df_sp.head())
df_sp.dtypes

   amfi_code                                   scheme_name       fund_house  \
0     119551     SBI Bluechip Fund - Regular Plan - Growth  SBI Mutual Fund
1     119552      SBI Bluechip Fund - Direct Plan - Growth  SBI Mutual Fund
2     119598    SBI Small Cap Fund - Regular Plan - Growth  SBI Mutual Fund
3     119599     SBI Small Cap Fund - Direct Plan - Growth  SBI Mutual Fund
4     119120  SBI Magnum Gilt Fund - Regular Plan - Growth  SBI Mutual Fund

    category     plan  return_1yr_pct  return_3yr_pct  return_5yr_pct  \
0  Large Cap  Regular           12.42           12.36           14.45
1  Large Cap   Direct           15.25           11.30           14.23
2  Small Cap  Regular           24.56           23.39           20.67
3  Small Cap   Direct           20.59           23.14           21.82
4       Gilt  Regular            5.34            6.07            5.43

   benchmark_3yr_pct  alpha  beta  sharpe_ratio  sortino_ratio  \
0              11.49   0.87  0.89          0.88           1.29
1               9.52   1.78  0.87          0.81           1.29
2              22.16   1.23  0.89          0.94           1.35
3              22.01   1.13  1.04          0.93           1.67
4               4.47   1.60  0.22          1.52           2.11

   std_dev_ann_pct  max_drawdown_pct  aum_crore  expense_ratio_pct  \
0             14.0            -21.70      14288               1.54
1             14.0            -24.43       1231               0.66
2             25.0            -13.35      19259               1.43
3             25.0            -24.78      36061               0.72
4              4.0             -2.30      24101               0.77

   morningstar_rating risk_grade
0                   4   Moderate
1                   3   Moderate
2                   5  Very High
3                   4  Very High
4                   5        Low

amfi_code               int64
scheme_name               str
fund_house                str
category                  str
plan                      str
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade                str
dtype: object

In [16]:
df_sp[df_sp['sharpe_ratio']<=0]
#no sharpe is negative

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [17]:
df_sp[df_sp['expense_ratio_pct'] <0.1]
df_sp[df_sp['expense_ratio_pct'] >2.5]
# all in range

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [18]:
df_sp.to_csv(wd/'clean_performance.csv',index=False)

In [19]:
#4th cleaning
df_fm = pd.read_csv(rd/'01_fund_master.csv')
print(df_fm.head())
df_fm.dtypes

   amfi_code       fund_house                                   scheme_name  \
0     119551  SBI Mutual Fund     SBI Bluechip Fund - Regular Plan - Growth
1     119552  SBI Mutual Fund      SBI Bluechip Fund - Direct Plan - Growth
2     119598  SBI Mutual Fund    SBI Small Cap Fund - Regular Plan - Growth
3     119599  SBI Mutual Fund     SBI Small Cap Fund - Direct Plan - Growth
4     119120  SBI Mutual Fund  SBI Magnum Gilt Fund - Regular Plan - Growth

  category sub_category     plan launch_date                  benchmark  \
0   Equity    Large Cap  Regular  2006-02-14              NIFTY 100 TRI
1   Equity    Large Cap   Direct  2013-01-01              NIFTY 100 TRI
2   Equity    Small Cap  Regular  2009-09-09       BSE 250 SmallCap TRI
3   Equity    Small Cap   Direct  2013-01-01       BSE 250 SmallCap TRI
4     Debt         Gilt  Regular  2000-12-30  CRISIL Dynamic Gilt Index

   expense_ratio_pct  exit_load_pct  min_sip_amount  min_lumpsum_amount  \
0               1.54            1.0             500                1000
1               0.66            1.0             500                1000
2               1.43            1.0             500                1000
3               0.72            1.0             500                1000
4               0.77            0.0             500                1000

    fund_manager risk_category sebi_category_code
0  Sohini Andani      Moderate               EC01
1  Sohini Andani      Moderate               EC01
2  R. Srinivasan     Very High               EC03
3  R. Srinivasan     Very High               EC03
4   Dinesh Ahuja           Low               DC02

amfi_code               int64
fund_house                str
scheme_name               str
category                  str
sub_category              str
plan                      str
launch_date               str
benchmark                 str
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager              str
risk_category             str
sebi_category_code        str
dtype: object

In [20]:
df_fm = df_fm.drop_duplicates()

In [21]:
df_fm['launch_date']=pd.to_datetime(df_fm['launch_date'])

In [22]:
df_fm.dtypes

amfi_code                      int64
fund_house                       str
scheme_name                      str
category                         str
sub_category                     str
plan                             str
launch_date           datetime64[us]
benchmark                        str
expense_ratio_pct            float64
exit_load_pct                float64
min_sip_amount                 int64
min_lumpsum_amount             int64
fund_manager                     str
risk_category                    str
sebi_category_code               str
dtype: object

In [23]:
#validating at a glance
for cols in df_fm.columns:
    print(df_fm[cols].unique())

[119551 119552 119598 119599 119120 100016 125497 100033 125498 100025
 120503 120504 120505 120506 120507 118632 118633 118634 118635 118636
 120841 120842 120843 120844 119092 119093 119094 119095 101206 101207
 101208 102885 102886 102887 148567 148568 148569 149322 149323 149324]
<StringArray>
[         'SBI Mutual Fund',         'HDFC Mutual Fund',
      'ICICI Prudential MF',          'Nippon India MF',
        'Kotak Mahindra MF',         'Axis Mutual Fund',
 'Aditya Birla Sun Life MF',          'UTI Mutual Fund',
           'Mirae Asset MF',          'DSP Mutual Fund']
Length: 10, dtype: str
<StringArray>
[            'SBI Bluechip Fund - Regular Plan - Growth',
              'SBI Bluechip Fund - Direct Plan - Growth',
            'SBI Small Cap Fund - Regular Plan - Growth',
             'SBI Small Cap Fund - Direct Plan - Growth',
          'SBI Magnum Gilt Fund - Regular Plan - Growth',
             'HDFC Top 100 Fund - Regular Plan - Growth',
              'HDFC Top 100 Fund - Direct Plan - Growth',
    'HDFC Mid-Cap Opportunities Fund - Regular - Growth',
     'HDFC Mid-Cap Opportunities Fund - Direct - Growth',
          'HDFC Short Term Debt Fund - Regular - Growth',
            'ICICI Pru Bluechip Fund - Regular - Growth',
             'ICICI Pru Bluechip Fund - Direct - Growth',
              'ICICI Pru Midcap Fund - Regular - Growth',
     'ICICI Pru Value Discovery Fund - Regular - Growth',
              'ICICI Pru Liquid Fund - Regular - Growth',
        'Nippon India Large Cap Fund - Regular - Growth',
         'Nippon India Large Cap Fund - Direct - Growth',
        'Nippon India Small Cap Fund - Regular - Growth',
                        'Nippon India ETF Nifty 50 BeES',
  'Nippon India Gilt Securities Fund - Regular - Growth',
                'Kotak Bluechip Fund - Regular - Growth',
         'Kotak Emerging Equity Fund - Regular - Growth',
                'Kotak Flexicap Fund - Regular - Growth',
                  'Kotak Liquid Fund - Regular - Growth',
                 'Axis Bluechip Fund - Regular - Growth',
                  'Axis Bluechip Fund - Direct - Growth',
                   'Axis Midcap Fund - Regular - Growth',
                'Axis Small Cap Fund - Regular - Growth',
         'ABSL Frontline Equity Fund - Regular - Growth',
                'ABSL Small Cap Fund - Regular - Growth',
                   'ABSL Liquid Fund - Regular - Growth',
            'UTI Nifty 50 Index Fund - Regular - Growth',
                   'UTI Mid Cap Fund - Regular - Growth',
                 'UTI Flexi Cap Fund - Regular - Growth',
         'Mirae Asset Large Cap Fund - Regular - Growth',
 'Mirae Asset Emerging Bluechip Fund - Regular - Growth',
         'Mirae Asset Tax Saver Fund - Regular - Growth',
            'DSP Top 100 Equity Fund - Regular - Growth',
                    'DSP Midcap Fund - Regular - Growth',
                 'DSP Small Cap Fund - Regular - Growth']
Length: 40, dtype: str
<StringArray>
['Equity', 'Debt']
Length: 2, dtype: str
<StringArray>
[      'Large Cap',       'Small Cap',            'Gilt',         'Mid Cap',
  'Short Duration',           'Value',          'Liquid',       'Index/ETF',
       'Flexi Cap',           'Index', 'Large & Mid Cap',            'ELSS']
Length: 12, dtype: str
<StringArray>
['Regular', 'Direct']
Length: 2, dtype: str
<DatetimeArray>
['2006-02-14 00:00:00', '2013-01-01 00:00:00', '2009-09-09 00:00:00',
 '2000-12-30 00:00:00', '1996-09-11 00:00:00', '2007-06-25 00:00:00',
 '2002-06-25 00:00:00', '2008-05-23 00:00:00', '2004-10-28 00:00:00',
 '2004-08-16 00:00:00', '2001-11-17 00:00:00', '2004-08-08 00:00:00',
 '2010-09-16 00:00:00', '2001-12-28 00:00:00', '1999-08-19 00:00:00',
 '2005-12-29 00:00:00', '2007-03-30 00:00:00', '2009-08-11 00:00:00',
 '2004-03-03 00:00:00', '2010-01-05 00:00:00', '2011-02-18 00:00:00',
 '2013-11-29 00:00:00', '2002-08-30 00:00:00', '2007-05-31 00:00:00',
 '2000-04-17 00:00:00', '2000-03-06 00:00:00', '2004-04-07 00:00:00',
 '2005-05-18 00:00:00', '2008-04-04 00:00:00', '2010-07-09 00:00:00',
 '2015-12-28 00:00:00', '2003-03-10 00:00:00', '2006-11-16 00:00:00',
 '2007-06-14 00:00:00']
Length: 34, dtype: datetime64[us]
<StringArray>
[               'NIFTY 100 TRI',         'BSE 250 SmallCap TRI',
    'CRISIL Dynamic Gilt Index',         'NIFTY Midcap 150 TRI',
 'CRISIL Short Term Bond Index',                'NIFTY 500 TRI',
  'CRISIL Liquid Fund AI Index',                 'NIFTY 50 TRI',
          'NIFTY Midcap 50 TRI',   'NIFTY Large Midcap 250 TRI']
Length: 10, dtype: str
[1.54 0.66 1.43 0.72 0.77 1.55 0.92 1.38 0.78 0.56 1.42 0.8  1.36 1.41
 0.74 1.51 1.53 0.89 0.55 1.59 1.56 1.45 0.6  1.64 0.75 1.6  0.79 1.57
 1.46 1.52 1.61]
[1.  0.  0.5]
[500]
[1000 5000  100]
<StringArray>
[      'Sohini Andani',       'R. Srinivasan',        'Dinesh Ahuja',
        'Rahul Baijal',     'Chirag Setalvad',        'Anil Bamboli',
      'Anish Tawakley',      'Sankaran Naren',       'Rahul Goswami',
    'Sailesh Raj Bhan',         'Samir Rachh',         'Vishal Jain',
        'Vivek Sharma',    'Harsha Upadhyaya',     'Pankaj Tibrewal',
      'Deepak Agrawal',   'Shreyash Devalkar',       'Jinesh Gopani',
       'Anupam Tiwari',        'Mahesh Patil',      'Mircea Ciobanu',
       'Maneesh Dangi', 'Sharwan Kumar Goyal',          'V Srivatsa',
          'Ajay Tyagi',        'Gaurav Misra',      'Neelesh Surana',
        'Apoorva Shah',        'Vinit Sambre']
Length: 29, dtype: str
<StringArray>
['Moderate', 'Very High', 'Low', 'High', 'Moderately High']
Length: 5, dtype: str
<StringArray>
['EC01', 'EC03', 'DC02', 'EC02', 'EC06', 'DC01', 'EI01', 'EC04', 'EC05']
Length: 9, dtype: str

In [24]:
df_fm.to_csv(wd/'clean_fund.csv',index=False)

In [25]:
#5th cleaning
df_fh = pd.read_csv(rd/'03_aum_by_fund_house.csv')
print(df_fh.head())
df_fh.dtypes

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

date                  str
fund_house            str
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object

In [26]:
#validating at a glance
for cols in df_fh.columns:
    print(df_fh[cols].unique())

<StringArray>
['2022-03-31', '2022-09-30', '2023-03-31', '2023-09-30', '2024-03-31',
 '2024-09-30', '2024-12-31', '2025-03-31', '2025-12-31']
Length: 9, dtype: str
<StringArray>
[         'SBI Mutual Fund',      'ICICI Prudential MF',
         'HDFC Mutual Fund',          'Nippon India MF',
        'Kotak Mahindra MF', 'Aditya Birla Sun Life MF',
         'Axis Mutual Fund',          'UTI Mutual Fund',
           'Mirae Asset MF',          'DSP Mutual Fund']
Length: 10, dtype: str
[ 6.05  4.65  4.35  2.7   2.78  2.5   2.3   1.05  1.1   6.3   4.88  4.45
  2.72  2.85  2.4   2.32  1.08  1.12  7.17  5.    4.5   2.93  2.89  2.75
  2.41  2.39  1.16  1.15  8.45  5.9   5.35  3.4   3.25  3.08  2.6   2.65
  1.42  1.32 10.    6.8   6.45  4.3   3.8   2.8   2.9   1.75  1.55 10.8
  7.42  7.1   4.68  4.05  3.62  1.9   1.72 11.14  8.74  7.87  5.7   4.89
  3.84  3.    3.52  2.1   1.88 12.5   8.8   7.95  5.6   4.92  3.85  3.1
  3.55  2.25  1.95 10.74  9.3   7.    5.8   4.6   3.5   4.1 ]
[ 605000  465000  435000  270000  278000  250000  230000  105000  110000
  630000  488000  445000  272000  285000  240000  232000  108000  112000
  717000  500000  450000  293000  289000  275000  241000  239000  116000
  115000  845000  590000  535000  340000  325000  308000  260000  265000
  142000  132000 1000000  680000  645000  430000  380000  280000  290000
  175000  155000 1080000  742000  710000  468000  405000  362000  190000
  172000 1114000  874000  787000  570000  489000  384000  300000  352000
  210000  188000 1250000  880000  795000  560000  492000  385000  310000
  355000  225000  195000 1074000  930000  700000  580000  460000  350000
  410000]
[186 216 195 177 168 199  95 142  56  88]

In [27]:
df_fh.to_csv(wd/'clean_aum.csv',index=False)

In [28]:
#6th cleaning
df_sip = pd.read_csv(rd/'04_monthly_sip_inflows.csv')
print(df_sip.head(24))
df_sip.dtypes

      month  sip_inflow_crore  active_sip_accounts_crore  \
0   2022-01             11517                       4.91
1   2022-02             11438                       4.93
2   2022-03             12328                       5.09
3   2022-04             11863                       5.48
4   2022-05             12286                       5.55
5   2022-06             12276                       5.60
6   2022-07             12140                       5.65
7   2022-08             12694                       5.71
8   2022-09             12976                       5.80
9   2022-10             13040                       5.93
10  2022-11             13306                       6.00
11  2022-12             13573                       6.05
12  2023-01             13856                       6.13
13  2023-02             13687                       6.19
14  2023-03             14276                       6.32
15  2023-04             14749                       6.41
16  2023-05             14749                       6.50
17  2023-06             14734                       6.55
18  2023-07             15245                       6.65
19  2023-08             15814                       6.73
20  2023-09             16042                       6.82
21  2023-10             16928                       6.91
22  2023-11             17073                       7.00
23  2023-12             17610                       7.10

    new_sip_accounts_lakh  sip_aum_lakh_crore  yoy_growth_pct
0                    9.10                4.80             NaN
1                    8.20                4.85             NaN
2                   10.50                5.01             NaN
3                    9.52                5.12             NaN
4                    8.10                5.15             NaN
5                    7.50                5.18             NaN
6                    9.21                5.25             NaN
7                    8.90                5.31             NaN
8                    9.40                5.41             NaN
9                    9.52                5.55             NaN
10                   8.80                5.62             NaN
11                   7.60                5.70             NaN
12                   9.10                5.82           20.31
13                   8.20                5.88           19.66
14                  10.00                6.01           15.80
15                   9.25                6.15           24.33
16                   8.70                6.22           20.05
17                   7.90                6.30           20.02
18                   9.80                6.45           25.58
19                   9.10                6.58           24.58
20                  10.20                6.72           23.63
21                   9.50                6.90           29.82
22                   8.80                7.05           28.31
23                   8.40                7.18           29.74

month                            str
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object

In [29]:
#validating at a glance
for cols in df_sip.columns:
    print(df_sip[cols].unique())

<StringArray>
['2022-01', '2022-02', '2022-03', '2022-04', '2022-05', '2022-06', '2022-07',
 '2022-08', '2022-09', '2022-10', '2022-11', '2022-12', '2023-01', '2023-02',
 '2023-03', '2023-04', '2023-05', '2023-06', '2023-07', '2023-08', '2023-09',
 '2023-10', '2023-11', '2023-12', '2024-01', '2024-02', '2024-03', '2024-04',
 '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10', '2024-11',
 '2024-12', '2025-01', '2025-02', '2025-03', '2025-04', '2025-05', '2025-06',
 '2025-07', '2025-08', '2025-09', '2025-10', '2025-11', '2025-12']
Length: 48, dtype: str
[11517 11438 12328 11863 12286 12276 12140 12694 12976 13040 13306 13573
 13856 13687 14276 14749 14734 15245 15814 16042 16928 17073 17610 18838
 19187 20371 21262 23332 23547 24509 25323 25320 26459 26400 25999 25926
 26632 26688 27274 28464 28265 29361 29529 30200 31002]
[4.91 4.93 5.09 5.48 5.55 5.6  5.65 5.71 5.8  5.93 6.   6.05 6.13 6.19
 6.32 6.41 6.5  6.55 6.65 6.73 6.82 6.91 7.   7.1  7.2  7.3  7.4  7.6
 7.78 7.9  8.   8.11 8.22 8.3  8.4  8.5  8.38 8.62 8.75 8.85 9.   9.1
 9.2  9.35]
[ 9.1   8.2  10.5   9.52  8.1   7.5   9.21  8.9   9.4   8.8   7.6  10.
  9.25  8.7   7.9   9.8  10.2   9.5   8.4   9.6   8.5   9.    9.2   9.55
  9.3   8.6   7.8  46.    9.45]
[ 4.8   4.85  5.01  5.12  5.15  5.18  5.25  5.31  5.41  5.55  5.62  5.7
  5.82  5.88  6.01  6.15  6.22  6.3   6.45  6.58  6.72  6.9   7.05  7.18
  7.35  7.52  7.71  7.9   8.15  8.35  8.56  8.78  8.98  9.22  9.45  9.7
 13.   13.18 13.35 13.55 13.72 13.88 14.05 15.18 15.38 15.55 15.72 15.9 ]
[  nan 20.31 19.66 15.8  24.33 20.05 20.02 25.58 24.58 23.63 29.82 28.31
 29.74 35.96 40.18 42.69 38.12 44.16 44.31 53.05 48.9  52.78 49.59 48.3
 50.25 40.14 35.5  27.27 30.73 25.52 28.28 22.   20.04 19.8  16.61 19.27
 17.17]

In [30]:
df_sip['yoy_growth_pct'].isna().sum()

np.int64(12)

In [31]:
df_sip = df_sip.fillna(0)

In [32]:
df_sip.head()

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,0.0
1,2022-02,11438,4.93,8.20,4.85,0.0
2,2022-03,12328,5.09,10.50,5.01,0.0
3,2022-04,11863,5.48,9.52,5.12,0.0
4,2022-05,12286,5.55,8.10,5.15,0.0

In [33]:
df_sip['month'] = pd.to_datetime(df_sip['month'], format='%Y-%m') + pd.offsets.MonthEnd(0)
df_sip

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01-31,11517,4.91,9.10,4.80,0.00
1,2022-02-28,11438,4.93,8.20,4.85,0.00
2,2022-03-31,12328,5.09,10.50,5.01,0.00
3,2022-04-30,11863,5.48,9.52,5.12,0.00
4,2022-05-31,12286,5.55,8.10,5.15,0.00
5,2022-06-30,12276,5.60,7.50,5.18,0.00
6,2022-07-31,12140,5.65,9.21,5.25,0.00
7,2022-08-31,12694,5.71,8.90,5.31,0.00
8,2022-09-30,12976,5.80,9.40,5.41,0.00
9,2022-10-31,13040,5.93,9.52,5.55,0.00
10,2022-11-30,13306,6.00,8.80,5.62,0.00
11,2022-12-31,13573,6.05,7.60,5.70,0.00
12,2023-01-31,13856,6.13,9.10,5.82,20.31
13,2023-02-28,13687,6.19,8.20,5.88,19.66
14,2023-03-31,14276,6.32,10.00,6.01,15.80
15,2023-04-30,14749,6.41,9.25,6.15,24.33
16,2023-05-31,14749,6.50,8.70,6.22,20.05
17,2023-06-30,14734,6.55,7.90,6.30,20.02
18,2023-07-31,15245,6.65,9.80,6.45,25.58
19,2023-08-31,15814,6.73,9.10,6.58,24.58
20,2023-09-30,16042,6.82,10.20,6.72,23.63
21,2023-10-31,16928,6.91,9.50,6.90,29.82
22,2023-11-30,17073,7.00,8.80,7.05,28.31
23,2023-12-31,17610,7.10,8.40,7.18,29.74
24,2024-01-31,18838,7.20,9.60,7.35,35.96
25,2024-02-29,19187,7.30,8.50,7.52,40.18
26,2024-03-31,20371,7.40,9.00,7.71,42.69
27,2024-04-30,20371,7.60,9.40,7.90,38.12
28,2024-05-31,21262,7.78,8.90,8.15,44.16
29,2024-06-30,21262,7.90,8.20,8.35,44.31
30,2024-07-31,23332,8.00,10.00,8.56,53.05
31,2024-08-31,23547,8.11,9.80,8.78,48.90
32,2024-09-30,24509,8.22,9.20,8.98,52.78
33,2024-10-31,25323,8.30,9.55,9.22,49.59
34,2024-11-30,25320,8.40,9.10,9.45,48.30
35,2024-12-31,26459,8.50,9.30,9.70,50.25
36,2025-01-31,26400,8.22,9.10,13.00,40.14
37,2025-02-28,25999,8.30,8.60,13.18,35.50
38,2025-03-31,25926,8.11,7.80,13.35,27.27
39,2025-04-30,26632,8.38,46.00,13.55,30.73
40,2025-05-31,26688,8.50,9.20,13.72,25.52
41,2025-06-30,27274,8.62,9.50,13.88,28.28
42,2025-07-31,28464,8.75,10.20,14.05,22.00
43,2025-08-31,28265,8.85,9.80,15.18,20.04
44,2025-09-30,29361,9.00,10.50,15.38,19.80
45,2025-10-31,29529,9.10,9.45,15.55,16.61
46,2025-11-30,30200,9.20,9.10,15.72,19.27
47,2025-12-31,31002,9.35,9.80,15.90,17.17

In [34]:
df_sip.to_csv(wd/'clean_sip.csv',index=False)

In [35]:
#7th cleaning
df_ci = pd.read_csv(rd/'05_category_inflows.csv')
print(df_ci.head(24))
df_ci.dtypes

      month           category  net_inflow_crore
0   2024-04          Large Cap            2413.0
1   2024-04            Mid Cap            3897.0
2   2024-04          Small Cap            3533.0
3   2024-04          Flexi Cap            4947.0
4   2024-04    Large & Mid Cap            4214.0
5   2024-04               ELSS             466.0
6   2024-04       Value/Contra            1328.0
7   2024-04  Sectoral/Thematic            8052.0
8   2024-04             Liquid           37537.0
9   2024-04     Short Duration            4400.0
10  2024-04               Gilt             784.0
11  2024-04             Hybrid            2955.0
12  2024-05          Large Cap            2076.0
13  2024-05            Mid Cap            5300.0
14  2024-05          Small Cap            4092.0
15  2024-05          Flexi Cap            5529.0
16  2024-05    Large & Mid Cap            4368.0
17  2024-05               ELSS             553.0
18  2024-05       Value/Contra            1361.0
19  2024-05  Sectoral/Thematic            8354.0
20  2024-05             Liquid           41872.0
21  2024-05     Short Duration            4833.0
22  2024-05               Gilt             836.0
23  2024-05             Hybrid            3487.0

month                   str
category                str
net_inflow_crore    float64
dtype: object

In [36]:
#validating at a glance
for cols in df_ci.columns:
    print(df_ci[cols].unique())

<StringArray>
['2024-04', '2024-05', '2024-06', '2024-07', '2024-08', '2024-09', '2024-10',
 '2024-11', '2024-12', '2025-01', '2025-02', '2025-03']
Length: 12, dtype: str
<StringArray>
[        'Large Cap',           'Mid Cap',         'Small Cap',
         'Flexi Cap',   'Large & Mid Cap',              'ELSS',
      'Value/Contra', 'Sectoral/Thematic',            'Liquid',
    'Short Duration',              'Gilt',            'Hybrid']
Length: 12, dtype: str
[ 2413.  3897.  3533.  4947.  4214.   466.  1328.  8052. 37537.  4400.
   784.  2955.  2076.  5300.  4092.  5529.  4368.   553.  1361.  8354.
 41872.  4833.   836.  3487.  2519.  5047.  3535.  4478.  4610.   472.
  1386. 10030. 40486.  4321.   864.  3163.  2574.  4548.  3582.  4869.
  5023.   471.  1582.  9896. 34643.  4170.   959.  3291.  1940.  3899.
  3376.  5562.  5411.   499.  1308.  8360. 41952.  4658.   952.  3684.
  1879.  4960.  4137.  5397.  4528.   537.  1334.  8518. 35308.  5327.
   925.  3015.  2255.  4106.  4444.  6004.  4581.  1595.  7680. 39091.
  4675.   898.  3314.  1870.  4336.  3256.  6111.  5556.   571.  1436.
  7397. 40506.  5316.   704.  3264.  1923.  4249.  4654.  4878.   521.
  1414.  9820. 34933.  4159.   831.  3538.  2025.  4316.  4554.  5603.
  4816.   516.  1339.  7893. 33892.  4752.   744.  2967.  1925.  4819.
  3534.  6068.  5524.   437.  1400.  9215. 32374.  4033.   942.  3360.
  2234.  5061.  4304.  4767.  4243.   500.  1497.  8614. 38681.  4886.
   956.  2830.]

In [37]:
df_ci['month'] = pd.to_datetime(df_ci['month'], format='%Y-%m') + pd.offsets.MonthEnd(0)
df_ci

         month           category  net_inflow_crore
0   2024-04-30          Large Cap            2413.0
1   2024-04-30            Mid Cap            3897.0
2   2024-04-30          Small Cap            3533.0
3   2024-04-30          Flexi Cap            4947.0
4   2024-04-30    Large & Mid Cap            4214.0
..         ...                ...               ...
139 2025-03-31  Sectoral/Thematic            8614.0
140 2025-03-31             Liquid           38681.0
141 2025-03-31     Short Duration            4886.0
142 2025-03-31               Gilt             956.0
143 2025-03-31             Hybrid            2830.0

[144 rows x 3 columns]

In [38]:
df_ci.to_csv(wd/'clean_category.csv',index=False)

In [39]:
#8th cleaning
df_ifc = pd.read_csv(rd/'06_industry_folio_count.csv')
print(df_ifc.head(24))
df_ifc.dtypes

      month  total_folios_crore  equity_folios_crore  debt_folios_crore  \
0   2022-01               13.26                 9.28               1.86
1   2022-04               13.91                 9.74               1.95
2   2022-07               13.85                 9.69               1.94
3   2022-10               14.12                 9.88               1.98
4   2023-01               14.81                10.37               2.07
5   2023-04               15.54                10.88               2.18
6   2023-07               16.28                11.40               2.28
7   2023-10               16.72                11.70               2.34
8   2024-01               17.78                12.45               2.49
9   2024-04               18.85                13.20               2.64
10  2024-07               19.98                13.99               2.80
11  2024-10               21.62                15.13               3.03
12  2024-12               22.89                16.02               3.20
13  2025-01               23.10                16.17               3.23
14  2025-03               23.45                16.42               3.28
15  2025-04               23.89                16.72               3.34
16  2025-07               24.57                17.20               3.44
17  2025-08               24.89                17.42               3.48
18  2025-09               25.19                17.63               3.53
19  2025-10               25.60                17.92               3.58
20  2025-12               26.12                18.28               3.66

    hybrid_folios_crore  others_folios_crore
0                  0.80                 1.33
1                  0.83                 1.39
2                  0.83                 1.38
3                  0.85                 1.41
4                  0.89                 1.48
5                  0.93                 1.55
6                  0.98                 1.63
7                  1.00                 1.67
8                  1.07                 1.78
9                  1.13                 1.89
10                 1.20                 2.00
11                 1.30                 2.16
12                 1.37                 2.29
13                 1.39                 2.31
14                 1.41                 2.35
15                 1.43                 2.39
16                 1.47                 2.46
17                 1.49                 2.49
18                 1.51                 2.52
19                 1.54                 2.56
20                 1.57                 2.61

month                      str
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object

In [40]:
df_ifc['month'] = pd.to_datetime(df_ifc['month'], format='%Y-%m') + pd.offsets.MonthEnd(0)
df_ifc

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01-31,13.26,9.28,1.86,0.80,1.33
1,2022-04-30,13.91,9.74,1.95,0.83,1.39
2,2022-07-31,13.85,9.69,1.94,0.83,1.38
3,2022-10-31,14.12,9.88,1.98,0.85,1.41
4,2023-01-31,14.81,10.37,2.07,0.89,1.48
5,2023-04-30,15.54,10.88,2.18,0.93,1.55
6,2023-07-31,16.28,11.40,2.28,0.98,1.63
7,2023-10-31,16.72,11.70,2.34,1.00,1.67
8,2024-01-31,17.78,12.45,2.49,1.07,1.78
9,2024-04-30,18.85,13.20,2.64,1.13,1.89
10,2024-07-31,19.98,13.99,2.80,1.20,2.00
11,2024-10-31,21.62,15.13,3.03,1.30,2.16
12,2024-12-31,22.89,16.02,3.20,1.37,2.29
13,2025-01-31,23.10,16.17,3.23,1.39,2.31
14,2025-03-31,23.45,16.42,3.28,1.41,2.35
15,2025-04-30,23.89,16.72,3.34,1.43,2.39
16,2025-07-31,24.57,17.20,3.44,1.47,2.46
17,2025-08-31,24.89,17.42,3.48,1.49,2.49
18,2025-09-30,25.19,17.63,3.53,1.51,2.52
19,2025-10-31,25.60,17.92,3.58,1.54,2.56
20,2025-12-31,26.12,18.28,3.66,1.57,2.61

In [41]:
df_ifc.to_csv(wd/'clean_industry.csv',index=False)

In [42]:
#9th cleaning
df_ph = pd.read_csv(rd/'09_portfolio_holdings.csv')
print(df_ph.head(24))
df_ph.dtypes

    amfi_code stock_symbol                     stock_name       sector  \
0      119551    POWERGRID         Power Grid Corporation    Utilities
1      119551     HDFCBANK                  HDFC Bank Ltd      Banking
2      119551       GRASIM          Grasim Industries Ltd  Diversified
3      119551      DRREDDY       Dr. Reddy's Laboratories       Pharma
4      119551   ASIANPAINT               Asian Paints Ltd       Paints
5      119551         NTPC                       NTPC Ltd    Utilities
6      119551     DIVISLAB            Divi's Laboratories       Pharma
7      119551   BHARTIARTL              Bharti Airtel Ltd      Telecom
8      119551      HCLTECH           HCL Technologies Ltd           IT
9      119551       MARUTI        Maruti Suzuki India Ltd   Automobile
10     119552         INFY                    Infosys Ltd           IT
11     119552    POWERGRID         Power Grid Corporation    Utilities
12     119552      DRREDDY       Dr. Reddy's Laboratories       Pharma
13     119552    ICICIBANK                 ICICI Bank Ltd      Banking
14     119552    TATAMOTOR                Tata Motors Ltd   Automobile
15     119552       MARUTI        Maruti Suzuki India Ltd   Automobile
16     119552        CIPLA                      Cipla Ltd       Pharma
17     119552     DIVISLAB            Divi's Laboratories       Pharma
18     119552   BAJFINANCE              Bajaj Finance Ltd         NBFC
19     119552    SUNPHARMA  Sun Pharmaceutical Industries       Pharma
20     119552   ULTRACEMCO           UltraTech Cement Ltd       Cement
21     119598        WIPRO                      Wipro Ltd           IT
22     119598          TCS      Tata Consultancy Services           IT
23     119598       GRASIM          Grasim Industries Ltd  Diversified

    weight_pct  market_value_cr  current_price_inr portfolio_date
0        13.85           737.09            6011.08     2025-12-31
1        11.19            88.97            1074.65     2025-12-31
2         9.90           208.45            5964.59     2025-12-31
3         4.76           161.32            3748.82     2025-12-31
4        10.25           725.90            1321.45     2025-12-31
5         7.48           897.70            2913.66     2025-12-31
6         3.21           286.44            3964.01     2025-12-31
7        13.94           452.19            5013.45     2025-12-31
8        18.22           177.35            6024.13     2025-12-31
9         7.20          1982.33            5461.85     2025-12-31
10       10.55           316.08            7088.71     2025-12-31
11        5.52           669.58            3434.04     2025-12-31
12        6.25           316.84            5910.04     2025-12-31
13       10.19          1006.69            4142.59     2025-12-31
14       17.88           484.41            4065.77     2025-12-31
15       14.60          1142.07            7620.26     2025-12-31
16       10.44          1019.41            7934.38     2025-12-31
17        7.39           208.30            1889.75     2025-12-31
18        5.86          1103.07            2693.54     2025-12-31
19        6.14          1136.79            6386.95     2025-12-31
20        5.19           780.54             927.58     2025-12-31
21       13.66           869.00            3504.41     2025-12-31
22        3.02           988.24            2581.10     2025-12-31
23        7.14           132.34            4515.26     2025-12-31

amfi_code              int64
stock_symbol             str
stock_name               str
sector                   str
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date           str
dtype: object

In [43]:
#validating at a glance
for cols in df_ph.columns:
    print(df_ph[cols].unique())

[119551 119552 119598 119599 100016 125497 100033 125498 120503 120504
 120505 120506 118632 118633 118634 118635 120841 120842 120843 119092
 119093 119094 119095 101206 101207 102885 102886 102887 148567 148568
 148569 149322 149323 149324]
<StringArray>
[ 'POWERGRID',   'HDFCBANK',     'GRASIM',    'DRREDDY', 'ASIANPAINT',
       'NTPC',   'DIVISLAB', 'BHARTIARTL',    'HCLTECH',     'MARUTI',
       'INFY',  'ICICIBANK',  'TATAMOTOR',      'CIPLA', 'BAJFINANCE',
  'SUNPHARMA', 'ULTRACEMCO',      'WIPRO',        'TCS',   'RELIANCE',
        'M&M',   'AXISBANK',  'KOTAKBANK',      'TITAN', 'HINDUNILVR',
 'INDUSINDBK',  'NESTLEIND',         'LT',       'SBIN',  'ADANIPORT']
Length: 30, dtype: str
<StringArray>
[       'Power Grid Corporation',                 'HDFC Bank Ltd',
         'Grasim Industries Ltd',      'Dr. Reddy's Laboratories',
              'Asian Paints Ltd',                      'NTPC Ltd',
           'Divi's Laboratories',             'Bharti Airtel Ltd',
          'HCL Technologies Ltd',       'Maruti Suzuki India Ltd',
                   'Infosys Ltd',                'ICICI Bank Ltd',
               'Tata Motors Ltd',                     'Cipla Ltd',
             'Bajaj Finance Ltd', 'Sun Pharmaceutical Industries',
          'UltraTech Cement Ltd',                     'Wipro Ltd',
     'Tata Consultancy Services',       'Reliance Industries Ltd',
       'Mahindra & Mahindra Ltd',                 'Axis Bank Ltd',
           'Kotak Mahindra Bank',             'Titan Company Ltd',
        'Hindustan Unilever Ltd',             'IndusInd Bank Ltd',
              'Nestle India Ltd',           'Larsen & Toubro Ltd',
           'State Bank of India',         'Adani Ports & SEZ Ltd']
Length: 30, dtype: str
<StringArray>
[     'Utilities',        'Banking',    'Diversified',         'Pharma',
         'Paints',        'Telecom',             'IT',     'Automobile',
           'NBFC',         'Cement',         'Energy', 'Consumer Goods',
           'FMCG', 'Infrastructure']
Length: 14, dtype: str
[13.85 11.19  9.9   4.76 10.25  7.48  3.21 13.94 18.22  7.2  10.55  5.52
  6.25 10.19 17.88 14.6  10.44  7.39  5.86  6.14  5.19 13.66  3.02  7.14
 16.5   5.32 15.16  8.18 10.96  3.56  7.19  5.59  3.71 10.69 18.56 13.47
  3.24  6.74  3.53 15.52 28.25 11.53  4.92  3.39 25.9   5.61  7.01 11.68
  6.09  9.03 14.84 12.53 12.03 10.03 11.81 19.04  5.02 14.65 14.89  4.66
 18.21  7.47  7.38 26.07  9.86  8.59 10.29  9.4   8.97  7.8  22.83  9.17
  6.39 20.91 14.53 15.87  5.68  9.26 15.92 20.69  9.98 10.22 12.38 14.52
  8.76 17.37  7.92  7.07  7.15 13.17  5.92  3.81  5.15 17.66  5.99 15.41
  7.25  4.96  8.   17.29 23.46  9.39 18.4   7.84  1.73  8.93 21.47  4.34
  6.98 20.94 11.98 10.91  4.44  6.57  9.85 13.33 30.44 12.5  11.14 12.43
  3.46 14.41  3.27 20.73  5.4   4.59  4.25 10.94  9.38 11.64  8.09  8.68
  3.13 12.26 11.75 13.59  8.64 12.32 14.28 13.45 15.83 17.85  8.39 10.07
 14.01  6.11  3.88  3.95  4.74  5.39  9.48  7.12 20.34  4.27 22.44 19.5
  7.27  3.73  6.77  3.72 13.09 18.15 11.62  8.98  7.16 16.74  6.43 15.39
  2.55 19.94  9.59  5.85  4.89  9.96  8.66  8.1   0.99 10.51 38.18 10.79
  4.49  4.24  3.55 16.39  4.36 14.79 10.28  2.57 10.68 10.52 20.22  6.64
  7.97 10.59  7.59 13.67 14.67 11.   23.17  5.89 16.75  7.7  17.8   7.76
  5.91  7.67  4.77  7.98 10.11 14.91 18.86 19.02  5.2   6.23  3.54 35.07
 19.26 10.31 12.01  4.84  2.7  14.32 21.75  7.05  5.26  7.11  1.38  6.59
 28.95 12.23  6.26  7.29  7.45 14.13  5.69 18.99 12.56  2.03 10.95  4.07
 19.31  8.37 10.14 19.73 12.16 10.78 12.63 11.42  8.49 10.05 22.93 12.18
 11.51 28.61 12.75 17.04  8.08  6.44 15.11  3.51 13.37 13.02  2.61 12.68
  7.63 25.53 14.12  7.51 11.83 18.28  3.48 10.85 17.77  9.43 14.66 10.5
  3.19 16.38 22.84  5.27 12.54  5.96  5.35  8.07 15.9   7.69  4.11  5.31
  5.79 17.19 19.71  6.95  9.54  1.79  2.04]
[ 737.09   88.97  208.45  161.32  725.9   897.7   286.44  452.19  177.35
 1982.33  316.08  669.58  316.84 1006.69  484.41 1142.07 1019.41  208.3
 1103.07 1136.79  780.54  869.    988.24  132.34  321.12 1392.64 1210.68
 1492.26 1665.15  682.95  751.31 1927.98 1751.14 1644.24 1254.17 1487.95
 1716.42  926.23 1123.22  825.04 1461.32  398.6  1325.34  169.92  552.43
 1102.98  214.89 1590.03  327.86  452.67  486.21  422.11 1652.67  115.8
  127.73  817.9  1316.71  985.86 1542.92  708.39 1815.93 1289.6   786.14
 1247.79  511.03  419.76  569.08  235.31  390.87  564.07 1897.59 1274.05
 1748.94  448.66 1577.15  960.23  994.44  746.26 1189.39  723.14 1320.03
 1137.55 1840.52 1672.96 1784.84  675.97 1715.09  168.11 1664.45 1236.71
 1433.51 1179.97 1250.03 1011.98  723.84 1067.82  286.97 1542.02  312.23
  585.69  419.93   55.74  598.91 1123.73  844.83 1369.31  551.04  274.26
 1709.46 1142.6  1436.98 1413.66  599.35  725.38  719.2  1774.48 1069.59
  857.97 1574.52 1293.86 1999.5  1593.88 1623.67  681.49  755.82 1703.38
  501.53 1071.93  550.74  863.48  442.46   64.71  418.49  784.14 1508.16
 1344.96 1855.52 1354.21  919.11  538.23  962.56 1471.49 1306.84  740.95
 1142.64 1806.09 1410.83  925.24  378.83  418.09  948.58 1070.67 1416.64
 1903.14 1874.06 1521.12 1740.32 1455.31 1315.89 1157.32  686.57 1199.27
 1444.86  383.65 1753.06 1100.59  776.8  1247.9  1561.91 1553.91 1827.52
 1534.27  803.14 1082.39  937.82  208.7  1039.97 1051.97 1091.16  501.88
   98.07 1860.16 1205.58 1254.8   886.68 1150.86 1507.25 1203.07 1290.15
  257.93  600.22  827.15 1790.66  483.92  342.31 1798.71 1393.54  622.91
  351.2  1508.82 1400.9  1966.9  1133.74  800.06  316.62 1619.58  252.39
 1148.78 1038.06  240.66 1606.74  329.49 1897.51 1468.69 1132.46  215.32
   68.79 1618.05  587.38 1665.13  282.61  487.84 1706.47 1436.08  172.92
  504.86 1473.28  519.75 1436.34  285.75 1295.94 1486.25  125.97 1615.91
  623.33  939.21   74.35  289.91  112.98 1831.03   60.84  300.72 1157.83
  686.86 1873.94  994.9  1519.3   109.7   214.19 1332.3   674.08 1899.26
  361.01 1559.12 1797.48 1621.24  432.92 1635.39 1593.15 1193.53 1051.37
  436.89 1660.53  512.93 1599.   1455.73  396.63 1543.57 1916.78 1920.78
 1638.77 1732.44 1076.44 1190.21  483.68 1005.62  498.31  345.42 1270.82
  716.33 1391.82 1779.28  780.09  940.8  1349.35  239.29  100.2  1097.74
  836.73  832.15  152.28 1604.94  421.51  827.19 1748.44 1637.54  377.91
  777.89 1731.8   136.25  915.39   92.02  533.85  704.58 1192.26 1277.89
  714.26 1913.58  516.02 1811.91 1707.37  663.04  405.18 1307.4  1289.52
 1576.26 1478.91  855.88  969.71 1637.69 1387.3  1303.55]
[6011.08 1074.65 5964.59 3748.82 1321.45 2913.66 3964.01 5013.45 6024.13
 5461.85 7088.71 3434.04 5910.04 4142.59 4065.77 7620.26 7934.38 1889.75
 2693.54 6386.95  927.58 3504.41 2581.1  4515.26  315.19 7901.22 7724.16
  660.82 2235.83 2504.73 1707.64 7369.33 5299.51 7387.94 3482.69 4137.4
 1982.11 7738.2  5235.31 5180.82 1872.83 2074.55 4188.12 4888.66  579.31
 6325.9   592.41 2555.06 6859.37 2212.6  5808.83 2280.96 1030.72 7583.81
 1212.79 1083.31 4748.8   341.2  7905.86 7817.51 7431.94 7294.22 6616.01
 3725.91 3852.87 2737.28 5010.14 3644.77 4339.96 2425.12 6636.11 3962.89
 7328.02 3097.29 7496.9  5902.74  897.71 7776.51  643.27 4111.6  5881.86
 5673.15 3918.12 4357.85 6042.94 2243.21 4875.9   246.78 4329.15 1131.45
 3674.34 3761.76 5095.49 5761.32 1687.26 6627.79 5145.8  3231.58  520.75
 5061.02 1215.8  3002.79 6868.09 5520.27 1002.08 4557.66 2246.21 4061.08
 1499.37 5665.46 7015.53 4390.56 7649.77 4476.73 2224.5   398.27 7863.69
 1607.57 6271.17 5022.73 2556.23 3276.69 4895.39 1451.32 2168.75 6184.87
 3746.36 5455.62  317.36 2546.04  920.38 7810.17 1132.14 1362.25 7745.28
 4192.5  5167.42 7435.21 1123.63 3625.67 3849.96 1563.4  7309.59 6309.28
 1403.66 5326.12 3004.71 3562.88 7044.44 6173.2  7250.24 6351.14 3952.67
 5923.09 6342.27 3894.14 1130.72 5157.09 4881.46 5915.73 4794.76 5242.17
 3083.92 7603.38 4666.99 2348.89  883.52  616.92 2078.2  6596.12 6429.58
 5130.67 5215.02 5570.96 6523.7  3745.54 5342.74 5621.65 4347.82 3725.98
 2259.4  3418.45  300.95 3939.8  5998.85 1288.77 4031.77 1713.52 2020.
 5191.92 7652.31 3058.71 6968.5  1252.99  812.36 1324.49 2861.09  489.5
 6889.63 7454.9  5764.34 5933.86 3188.56 3809.11 5747.11 6315.88  396.01
 6033.63  269.84 1689.13 4843.32 2449.17 5641.17 5378.47 1972.37 5510.02
 5423.86  459.87 1128.83 6272.04 4680.8  6609.49 3295.1  6762.78 5588.68
  854.49 1335.09 5034.91 4697.14 5455.74 1039.64  364.82 7023.37 2852.68
 2445.29 7103.06 4843.16 4924.89 5206.32 5143.85  437.69 6989.33 1089.14
 5523.71 2243.25 4140.59 5784.12 5666.75 1841.42 2766.01 2946.22 7301.8
 6161.34 3495.4  4089.04  438.37  734.47 4619.66 7144.77 3304.74  438.41
 3243.62  768.79 3567.17 2093.34 4842.   7059.58 1910.05 4502.46 2358.55
 7509.2  5968.64  247.69  536.81 6617.15 1183.81 2893.58 7832.89 7469.46
 5245.19 5973.41 1990.   6804.51 1757.42 1078.77 7246.42 2456.65 5166.81
 2983.88 5736.45  428.19 7241.49 5461.49 4418.19 3372.6  1226.98 2025.88
 7819.47 1285.32 4506.37 5031.45 4127.8  5346.17 2142.27 1276.16 7922.62
 1080.51 2703.69 4967.72 5960.44 3007.37 7942.96 6979.57 2911.62 1556.49
 1803.18 2762.54 7453.05  924.41 1927.89 3208.86 5797.95]
<StringArray>
['2025-12-31']
Length: 1, dtype: str

In [44]:
df_ph.to_csv(wd/'clean_portfoilio.csv',index=False)

In [45]:
#10th cleaning
df_bi = pd.read_csv(rd/'10_benchmark_indices.csv')
print(df_bi.head(24))
df_bi.dtypes

          date index_name  close_value
0   2022-01-03    NIFTY50     17492.79
1   2022-01-04    NIFTY50     17689.64
2   2022-01-05    NIFTY50     17835.05
3   2022-01-06    NIFTY50     17878.51
4   2022-01-07    NIFTY50     17759.15
5   2022-01-10    NIFTY50     18124.84
6   2022-01-11    NIFTY50     18256.96
7   2022-01-12    NIFTY50     18162.54
8   2022-01-13    NIFTY50     18179.05
9   2022-01-14    NIFTY50     17971.75
10  2022-01-17    NIFTY50     17998.26
11  2022-01-18    NIFTY50     17938.46
12  2022-01-19    NIFTY50     18301.33
13  2022-01-20    NIFTY50     18424.66
14  2022-01-21    NIFTY50     18055.59
15  2022-01-24    NIFTY50     18338.54
16  2022-01-25    NIFTY50     18408.04
17  2022-01-26    NIFTY50     18650.54
18  2022-01-27    NIFTY50     18701.92
19  2022-01-28    NIFTY50     18734.13
20  2022-01-31    NIFTY50     18615.38
21  2022-02-01    NIFTY50     18724.17
22  2022-02-02    NIFTY50     18900.90
23  2022-02-03    NIFTY50     18640.35

date               str
index_name         str
close_value    float64
dtype: object

In [46]:
#validating at a glance
for cols in df_bi.columns:
    print(df_bi[cols].unique())

<StringArray>
['2022-01-03', '2022-01-04', '2022-01-05', '2022-01-06', '2022-01-07',
 '2022-01-10', '2022-01-11', '2022-01-12', '2022-01-13', '2022-01-14',
 ...
 '2026-05-18', '2026-05-19', '2026-05-20', '2026-05-21', '2026-05-22',
 '2026-05-25', '2026-05-26', '2026-05-27', '2026-05-28', '2026-05-29']
Length: 1150, dtype: str
<StringArray>
[        'NIFTY50',        'NIFTY100', 'NIFTY_MIDCAP150',    'BSE_SMALLCAP',
        'NIFTY500',   'CRISIL_LIQUID',     'CRISIL_GILT']
Length: 7, dtype: str
[17492.79 17689.64 17835.05 ...  2281.3   2298.35  2302.79]

In [47]:
df_bi['date']=pd.to_datetime(df_bi['date'])

In [48]:
df_bi[df_bi['close_value']<=0]

Empty DataFrame
Columns: [date, index_name, close_value]
Index: []

In [49]:
df_bi.to_csv(wd/'clean_benchmark.csv',index=False)